services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU:ru
      - LC_ALL=ru_RU.UTF-8
      - TOKEN=${TOKEN}
      - BOT_ADDRESS=${BOT_ADDRESS}
      - ADMINS=${ADMINS}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - GROUP_CHAT_ID=${GROUP_CHAT_ID}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AERICH_TORTOISE_ORM=app.database.database.CONFIG
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "aerich upgrade && python3 main.py"
    volumes:
      - .:/app
  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5455:5432
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data: